### ISSUE TITLE
What Are the Relationships Between ModelArts and Other Services: missing hyperlinks

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/modelarts#19]
Issue on page: https://github.com/opentelekomcloud-docs/modelarts/blob/main/umn/source/faqs/general_issues/what_are_the_relationships_between_modelarts_and_other_services.rst

similar issue like https://github.com/opentelekomcloud-docs/modelarts/issues/7

**Comment by kucerakk** [comment]
Old HC source defines a href value for links : https://docs.otc.t-systems.com/usermanual/modelarts/modelarts_05_0003.html

![image](https://user-images.githubusercontent.com/8899650/164167832-598e941c-e488-4ecd-ac21-2062e3c0e269.png)

However the source what has been used to generate new HC3.0 is missing this href entry:

https://github.com/opentelekomcloud-docs/doc-exports/blob/main/modelarts/umn/modelarts_05_0003.html

This issue is clearly related to the source html files and not the conversion itself.
